/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IdentityStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessRequests"
      | "fieldAccess"
      | "incomingRequests"
      | "outgoingRequests"
      | "profileOwners"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accessRequests",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fieldAccess",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incomingRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outgoingRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "profileOwners",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "accessRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fieldAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incomingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outgoingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileOwners",
    data: BytesLike
  ): Result;
}

export interface IdentityStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityStorage;
  waitForDeployment(): Promise<this>;

  interface: IdentityStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        message: string;
        timestamp: bigint;
        pending: boolean;
        granted: boolean;
      }
    ],
    "view"
  >;

  fieldAccess: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  incomingRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  outgoingRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  profileOwners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        message: string;
        timestamp: bigint;
        pending: boolean;
        granted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fieldAccess"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "incomingRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "outgoingRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "profileOwners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
