/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProfile"
      | "getAccessRequestStatus"
      | "getAllProfileOwners"
      | "getGrantedFields"
      | "getMyIncomingRequests"
      | "getMyOutgoingRequests"
      | "getMyProfile"
      | "getPendingFieldHandle"
      | "grantAccess"
      | "hasProfile"
      | "requestAccess"
      | "requestFieldDecryption"
      | "revokeAccess"
      | "submitFieldDecryption"
      | "updateProfile"
      | "viewSharedField"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRequested"
      | "AccessRevoked"
      | "FieldDecrypted"
      | "FieldMarkedForDecryption"
      | "ProfileCreated"
      | "ProfileUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessRequestStatus",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProfileOwners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGrantedFields",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyIncomingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyOutgoingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingFieldHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFieldDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFieldDecryption",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "viewSharedField",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessRequestStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProfileOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGrantedFields",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyIncomingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyOutgoingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingFieldHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFieldDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFieldDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewSharedField",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    dataOwner: AddressLike,
    requester: AddressLike,
    fields: BigNumberish[]
  ];
  export type OutputTuple = [
    dataOwner: string,
    requester: string,
    fields: bigint[]
  ];
  export interface OutputObject {
    dataOwner: string;
    requester: string;
    fields: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRequestedEvent {
  export type InputTuple = [
    requester: AddressLike,
    dataOwner: AddressLike,
    message: string
  ];
  export type OutputTuple = [
    requester: string,
    dataOwner: string,
    message: string
  ];
  export interface OutputObject {
    requester: string;
    dataOwner: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [dataOwner: AddressLike, requester: AddressLike];
  export type OutputTuple = [dataOwner: string, requester: string];
  export interface OutputObject {
    dataOwner: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FieldDecryptedEvent {
  export type InputTuple = [
    owner: AddressLike,
    field: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, field: bigint, value: bigint];
  export interface OutputObject {
    owner: string;
    field: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FieldMarkedForDecryptionEvent {
  export type InputTuple = [owner: AddressLike, field: BigNumberish];
  export type OutputTuple = [owner: string, field: bigint];
  export interface OutputObject {
    owner: string;
    field: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProfile: TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getAccessRequestStatus: TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        exists: boolean;
        pending: boolean;
        granted: boolean;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAllProfileOwners: TypedContractMethod<[], [string[]], "view">;

  getGrantedFields: TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [boolean[]],
    "view"
  >;

  getMyIncomingRequests: TypedContractMethod<[], [string[]], "view">;

  getMyOutgoingRequests: TypedContractMethod<[], [string[]], "view">;

  getMyProfile: TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, string] & {
        emailHandle: string;
        dobHandle: string;
        nameHandle: string;
        idNumberHandle: string;
        locationHandle: string;
        experienceHandle: string;
        countryHandle: string;
      }
    ],
    "view"
  >;

  getPendingFieldHandle: TypedContractMethod<
    [field: BigNumberish],
    [string],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [requester: AddressLike, fields: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  hasProfile: TypedContractMethod<[owner: AddressLike], [boolean], "view">;

  requestAccess: TypedContractMethod<
    [dataOwner: AddressLike, message: string],
    [void],
    "nonpayable"
  >;

  requestFieldDecryption: TypedContractMethod<
    [field: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [requester: AddressLike],
    [void],
    "nonpayable"
  >;

  submitFieldDecryption: TypedContractMethod<
    [field: BigNumberish, decryptedValue: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  viewSharedField: TypedContractMethod<
    [dataOwner: AddressLike, field: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProfile"
  ): TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccessRequestStatus"
  ): TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        exists: boolean;
        pending: boolean;
        granted: boolean;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProfileOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGrantedFields"
  ): TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [boolean[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyIncomingRequests"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMyOutgoingRequests"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMyProfile"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, string] & {
        emailHandle: string;
        dobHandle: string;
        nameHandle: string;
        idNumberHandle: string;
        locationHandle: string;
        experienceHandle: string;
        countryHandle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingFieldHandle"
  ): TypedContractMethod<[field: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [requester: AddressLike, fields: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestAccess"
  ): TypedContractMethod<
    [dataOwner: AddressLike, message: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestFieldDecryption"
  ): TypedContractMethod<[field: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<[requester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitFieldDecryption"
  ): TypedContractMethod<
    [field: BigNumberish, decryptedValue: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewSharedField"
  ): TypedContractMethod<
    [dataOwner: AddressLike, field: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRequested"
  ): TypedContractEvent<
    AccessRequestedEvent.InputTuple,
    AccessRequestedEvent.OutputTuple,
    AccessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "FieldDecrypted"
  ): TypedContractEvent<
    FieldDecryptedEvent.InputTuple,
    FieldDecryptedEvent.OutputTuple,
    FieldDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "FieldMarkedForDecryption"
  ): TypedContractEvent<
    FieldMarkedForDecryptionEvent.InputTuple,
    FieldMarkedForDecryptionEvent.OutputTuple,
    FieldMarkedForDecryptionEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address,uint8[])": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRequested(address,address,string)": TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;
    AccessRequested: TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;

    "AccessRevoked(address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "FieldDecrypted(address,uint8,uint64)": TypedContractEvent<
      FieldDecryptedEvent.InputTuple,
      FieldDecryptedEvent.OutputTuple,
      FieldDecryptedEvent.OutputObject
    >;
    FieldDecrypted: TypedContractEvent<
      FieldDecryptedEvent.InputTuple,
      FieldDecryptedEvent.OutputTuple,
      FieldDecryptedEvent.OutputObject
    >;

    "FieldMarkedForDecryption(address,uint8)": TypedContractEvent<
      FieldMarkedForDecryptionEvent.InputTuple,
      FieldMarkedForDecryptionEvent.OutputTuple,
      FieldMarkedForDecryptionEvent.OutputObject
    >;
    FieldMarkedForDecryption: TypedContractEvent<
      FieldMarkedForDecryptionEvent.InputTuple,
      FieldMarkedForDecryptionEvent.OutputTuple,
      FieldMarkedForDecryptionEvent.OutputObject
    >;

    "ProfileCreated(address,uint256)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ProfileUpdated(address,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
  };
}
