/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessRequests"
      | "confidentialProtocolId"
      | "createProfile"
      | "fieldAccess"
      | "getAccessRequestStatus"
      | "getAllProfileOwners"
      | "getEncryptedField"
      | "getGrantedFields"
      | "getMyIncomingRequests"
      | "getMyOutgoingRequests"
      | "getMyProfile"
      | "grantAccess"
      | "hasProfile"
      | "incomingRequests"
      | "outgoingRequests"
      | "profileOwners"
      | "requestAccess"
      | "revokeAccess"
      | "updateProfile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRequested"
      | "AccessRevoked"
      | "ProfileCreated"
      | "ProfileUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessRequests",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fieldAccess",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessRequestStatus",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProfileOwners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedField",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrantedFields",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyIncomingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyOutgoingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incomingRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outgoingRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "profileOwners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "accessRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fieldAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessRequestStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProfileOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedField",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGrantedFields",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyIncomingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyOutgoingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incomingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outgoingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    dataOwner: AddressLike,
    requester: AddressLike,
    fields: BigNumberish[]
  ];
  export type OutputTuple = [
    dataOwner: string,
    requester: string,
    fields: bigint[]
  ];
  export interface OutputObject {
    dataOwner: string;
    requester: string;
    fields: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRequestedEvent {
  export type InputTuple = [
    requester: AddressLike,
    dataOwner: AddressLike,
    message: string
  ];
  export type OutputTuple = [
    requester: string,
    dataOwner: string,
    message: string
  ];
  export interface OutputObject {
    requester: string;
    dataOwner: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [dataOwner: AddressLike, requester: AddressLike];
  export type OutputTuple = [dataOwner: string, requester: string];
  export interface OutputObject {
    dataOwner: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        message: string;
        timestamp: bigint;
        pending: boolean;
        granted: boolean;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createProfile: TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  fieldAccess: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  getAccessRequestStatus: TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        exists: boolean;
        pending: boolean;
        granted: boolean;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAllProfileOwners: TypedContractMethod<[], [string[]], "view">;

  getEncryptedField: TypedContractMethod<
    [dataOwner: AddressLike, field: BigNumberish],
    [string],
    "view"
  >;

  getGrantedFields: TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [boolean[]],
    "view"
  >;

  getMyIncomingRequests: TypedContractMethod<[], [string[]], "view">;

  getMyOutgoingRequests: TypedContractMethod<[], [string[]], "view">;

  getMyProfile: TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, string] & {
        emailHandle: string;
        dobHandle: string;
        nameHandle: string;
        idNumberHandle: string;
        locationHandle: string;
        experienceHandle: string;
        countryHandle: string;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [requester: AddressLike, fields: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  hasProfile: TypedContractMethod<[owner: AddressLike], [boolean], "view">;

  incomingRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  outgoingRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  profileOwners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  requestAccess: TypedContractMethod<
    [dataOwner: AddressLike, message: string],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [requester: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        message: string;
        timestamp: bigint;
        pending: boolean;
        granted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProfile"
  ): TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fieldAccess"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessRequestStatus"
  ): TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        exists: boolean;
        pending: boolean;
        granted: boolean;
        message: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllProfileOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEncryptedField"
  ): TypedContractMethod<
    [dataOwner: AddressLike, field: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGrantedFields"
  ): TypedContractMethod<
    [dataOwner: AddressLike, requester: AddressLike],
    [boolean[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyIncomingRequests"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMyOutgoingRequests"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMyProfile"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string, string] & {
        emailHandle: string;
        dobHandle: string;
        nameHandle: string;
        idNumberHandle: string;
        locationHandle: string;
        experienceHandle: string;
        countryHandle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [requester: AddressLike, fields: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "incomingRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "outgoingRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "profileOwners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "requestAccess"
  ): TypedContractMethod<
    [dataOwner: AddressLike, message: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<[requester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<
    [
      encryptedEmail: BytesLike,
      encryptedDob: BytesLike,
      encryptedName: BytesLike,
      encryptedIdNumber: BytesLike,
      encryptedLocation: BytesLike,
      encryptedExperience: BytesLike,
      encryptedCountry: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRequested"
  ): TypedContractEvent<
    AccessRequestedEvent.InputTuple,
    AccessRequestedEvent.OutputTuple,
    AccessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address,uint8[])": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRequested(address,address,string)": TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;
    AccessRequested: TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;

    "AccessRevoked(address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "ProfileCreated(address,uint256)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ProfileUpdated(address,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
  };
}
